KEY_VALUE_DELIMITER = "="
VALUE_DELIMITER = ","
START_BLOCK_CHART = "{"
END_BLOCK_CHART = "}"
BP_EXTENSIONS = ".bp"
GLOBAL_NAME_STRUCTURE = r"^\w+\s*{"
GITHUB_UNIT_URL = "https://api.github.com/repos/FAForever/fa/contents"
